---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: reddos
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora-ostree-desktops/base-atomic
image-version: 41 # latest version

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: bling
    install:
        - rpmfusion # install RPMFusion repos, including tainted repos & disable negativo17 repos if installed

  - type: rpm-ostree
    install:
      - bspwm
      - sxhkd
      - picom
      - rofi
      - polybar
      - dunst
      - fish
      - sddm
      - kitty
      - curl
      - wget
      - gcc
      - akmod-nvidia 
      - xorg-x11-drv-nvidia-cuda
  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - io.github.zen_browser.zen
        - com.spotify.Client
        - com.discordapp.Discord
        - com.visualstudio.code
        - org.fcitx.Fcitx5
        - org.fcitx.Fcitx5.Addon.McBopomofo
    user: {} # Also add Flathub user repo, but no user packages

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans

  - type: brew
    nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry

  - type: signing # this sets up the proper policy & signing files for signed images to work fully


